spring:
    application:
        name: bootall
    profiles:
        active: dev
        include: mac

    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: bootall
        password: bootall
        url: jdbc:mysql://localhost:3306/boot-all
        name: mysqlDatasource
    jpa:
        open-in-view: true #默认为true 通过OpenEntityManagerInViewInterceptor拦截器实现 在WEB环境才起作用
        show-sql: true
        database: mysql
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
            use-new-id-generator-mappings: false
            naming:
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy #逻辑名称
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy #物理名称
        properties:
            hibernate:
                format_sql: true

logging:
    level:
        root: info
        com.dtxytech: debug



